<script lang="ts">

    // --- Logic ---
    import { cn } from '@lib/utils';
    import type { RowProps } from ".."
    
    let {
        children,
        class: className,
        rowClass = $bindable('flex flex-row'),
        // Events
        onclick = () => {},
        onmouseenter = () => {},
        onmouseleave = () => {},
        // Catchall
        ...rest
    }: RowProps & any = $props();


    // Setup Row's class
    let rowCls = $state(cn(rowClass, className));
    $effect(() => {
        rowCls = cn(rowClass, className)
    })

</script>

<!-- svelte-ignore a11y_click_events_have_key_events -->
<!-- svelte-ignore a11y_no_static_element_interactions -->
<div class={ rowCls } {onclick} {onmouseenter} {onmouseleave} {...rest}>
    {@render children?.()}
</div>

<!--@component
    Generated by SvelteForge🔥
-->

