<script lang="ts">

    // --- Logic ---
    import { cn } from '@lib/utils';
    import type { ColumnProps } from ".."
    
    let {
        children,
        class: className,
        columnClass = $bindable('flex flex-col'),
        // Events
        onclick = () => {},
        onmouseenter = () => {},
        onmouseleave = () => {},
        
        // Catchall
        ...rest
    }: ColumnProps & any = $props();


    // Setup Column's class
    let columnCls = $state(cn(columnClass, className));
    $effect(() => {
        columnCls = cn(columnClass, className)
    })

</script>

<!-- svelte-ignore a11y_no_static_element_interactions -->
<!-- svelte-ignore a11y_click_events_have_key_events -->
<div class={ columnCls } {onclick} {onmouseenter} {onmouseleave} {...rest}>
    {@render children?.()}
</div>

<!--@component
    Generated by SvelteForge🔥
-->

