<script lang="ts">
	// --- Logic ---
	import { cn } from '@lib/utils';
	import type { ButtonProps } from '..';
	import { Flex } from '@ui';

	let {
		children,
		class: className,
		buttonClass = $bindable('size-50 rounded-full items-center content-center bg-amber-200')
	}: ButtonProps = $props();

	// Setup Button's class
	let buttonCls = $state(cn(buttonClass, className));
	$effect(() => {
		buttonCls = cn(buttonClass, className);
	});
</script>

<Flex.Col class={buttonCls}>
	<!-- Actual Icon Svg -->
	{@render children?.()}
</Flex.Col>

<!--@component
    Generated by SvelteForge🔥
-->
