<script lang="ts">

    // --- Logic ---
    import { cn } from '@lib/utils';
    import type { Props } from ".."
    
    let {
        children,
        class: className,
        windowControlClass = $bindable('')
    }: Props & any = $props();


    // Setup WindowControl's class
    let windowControlCls = $state(cn(windowControlClass, className));
    $effect(() => {
        windowControlCls = cn(windowControlClass, className)
    })

</script>

<div class={ windowControlCls }>
    {@render children?.()}
</div>

<!--@component
    Generated by SvelteForge🔥
-->

