<script lang="ts">

    // --- Logic ---
    import { cn } from '@lib/utils';
    import type { Props } from ".."
    
    let {
        children,
        class: className,
        separatorClass = $bindable('size-full')
    }: Props = $props();


    // Setup Separator's class
    let separatorCls = $state(cn(separatorClass, className));
    $effect(() => {
        separatorCls = cn(separatorClass, className)
    })

</script>

<div class={ separatorCls }>
    {@render children?.()}
</div>

<!--@component
    Generated by SvelteForge🔥
-->

