<script lang="ts">

    // --- Logic ---
    import { cn } from '@lib/utils';
    import type { Props } from ".."
    
    let {
        children,
        class: className,
        flex = $bindable(undefined),
        row = $bindable(undefined),
        col = $bindable(undefined),
        center = $bindable(undefined),
        centerx = $bindable(undefined),
        centery = $bindable(undefined),
        fill = $bindable(undefined),
        fillw = $bindable(undefined),
        fillh = $bindable(undefined),
        noshrink = $bindable(undefined),
        aspectSquare = $bindable(undefined),
        cursorAuto = $bindable(undefined),
        cursorDefault = $bindable(undefined),
        cursorPointer = $bindable(undefined),
        ...rest
    }: Props = $props();

    function addTokenIf(statement: any, token: string) {
        if (statement === true) {
            className += ` ${token}`
        }
    }

    // Flex Box
    addTokenIf(flex, 'flex')
    addTokenIf(row, 'flex-row')
    addTokenIf(col, 'flex-col')

    // Positioning
    addTokenIf(center, 'items-center justify-center')
    addTokenIf(centerx, 'items-center')
    addTokenIf(centery, 'justify-center')

    // Size Fillings 
    addTokenIf(fill, 'size-full')
    addTokenIf(fillw, 'w-full')
    addTokenIf(fillh, 'h-full')

    // Flex Config
    addTokenIf(noshrink, 'shrink-0')

    // Aspect Ratios
    addTokenIf(aspectSquare, 'aspect-square')

    // Cursor Options
    addTokenIf(cursorAuto, 'cursor-auto')
    addTokenIf(cursorDefault, 'cursor-default')
    addTokenIf(cursorPointer, 'cursor-pointer')
</script>

<div class={ cn(className) } {...rest}>
    {@render children?.()}
</div>

<!--@component
    Generated by SvelteForge🔥
-->

