<script lang="ts">
	// --- Components ---
	import { Frame } from '@ui';

	// --- Logic ---
	import { cn } from '@lib/utils';
	import type { CircleProps } from '..';

	let { children, class: className, circleClass = $bindable('rounded-full size-4'), ...rest }: CircleProps = $props();

	// Setup Circle's class
	let circleCls = $state(cn(circleClass, className));
	$effect(() => {
		circleCls = cn(circleClass, className);
	});

</script>

<Frame class={cn(circleCls)} {...rest} noshrink>
	{@render children?.()}
</Frame>

<!--@component
    Generated by SvelteForge🔥
-->
