<script lang="ts">
	// --- Components ---
	import { Flex } from '@ui';

	// --- Logic ---
	import { cn } from '@lib/utils';
	import type { Props } from '..';

	let { children, class: className }: Props = $props();
</script>

<Flex.Row
	class={cn('w-full h-12 border-0 border-b border-depth-2', className)}
	data-tauri-drag-region
>
	{@render children?.()}
</Flex.Row>
<!--@component
    Generated by SvelteForge🔥


-->
