<script lang="ts">
	// --- Logic ---
	import { cn } from '@lib/utils';
	import type { WindowControlProps } from '..';
	import { getContext } from 'svelte';

	let {
		children,
		class: className,
		windowControlClass = $bindable('flex flex-row items-center justify-center h-full aspect-square transition-all ease-in-out'),
		...rest
	}: WindowControlProps = $props();

	// Setup WindowControl's class
	let windowControlCls = $state(cn(windowControlClass, className));
	$effect(() => {
		windowControlCls = cn(windowControlClass, className);
	});

	let context_class = getContext('class-titlebar-window-control')
</script>

<button class={cn(context_class, windowControlCls)} {...rest}>
	{@render children?.()}
</button>

<!--@component
    Generated by SvelteForge🔥
-->
