<script lang="ts">
	// --- Components ---
	import { Flex, Frame, Shape } from '@ui';

	// --- Logic ---
	import { cn } from '@lib/utils';
	import type { Props } from '..';

	let { children, class: className }: Props = $props();
</script>

<Frame
	flex
	col
	fillh
	noshrink
	class={cn('w-12 bg-component-sidebar border-0 border-r border-depth-2', className)}
>
	<!-- Icon Placeholder -->
	<Frame flex row center fillw aspectSquare noshrink>
		<Shape.Circle class="bg-primary" cursorPointer/>
	</Frame>

	{@render children?.()}
</Frame>

<!--@component
    Generated by SvelteForge🔥
-->
